import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const ShareTechMono = localFont({
  src: '../../public/fonts/ShareTechMono-Regular.ttf'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${ShareTechMono.className} antialiased bg-white dark:bg-slate-900`}
      >
        {children}
      </body>
    </html>
  );
}
